name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: Bootstrap
          run: |
            ./bootstrap.sh
        - name: Run tests
          run: |
            export PATH=$(pwd)/packages/python/bin:${PATH}
            export PATH=$(pwd)/packages/verilator/bin:${PATH}

            ./sv/hello_world/runit_vlt.sh



